Ensure action fails when internal steps do (#35)
Fixes #34, which is apparently a regression introduced in #29
(https://github.com/Firehed/multistage-docker-build-action/pull/35/commits/20c0bcdf75ca97975bb15b2278e50ebaeee66670).

This also adds `eslint` which would likely have caught the issue
earlier.

diff --git a/.github/workflows/self-test-multistage-docker-build.yml b/.github/workflows/self-test-multistage-docker-build.yml
--- a/.github/workflows/self-test-multistage-docker-build.yml
+++ b/.github/workflows/self-test-multistage-docker-build.yml
@@ -174,3 +174,52 @@ jobs:
 
       - name: Run image
         run: docker run --rm ${{ steps.build.outputs.server-tag }}
+
+  expect-error-build-failure:
+    name: Action should fail if docker build fails
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Auth to GH registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - uses: ./
+        name: Build with bad settings
+        continue-on-error: true
+        id: build
+        with:
+          # No context/dockerfile
+          server-stage: server
+          repository: ghcr.io/firehed/actions
+
+      - name: expect failure
+        if: steps.build.outcome == 'success'
+        run: exit 1
+
+
+  expect-error-push-failure:
+    name: Action should fail if docker push fails
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      # Do not log in to docker registry. This will cause the push to fail
+
+      - uses: ./
+        name: Build without login
+        continue-on-error: true
+        id: build
+        with:
+          context: examples
+          repository: ghcr.io/firehed/actions
+          stages: env, configured
+          server-stage: server
+
+      - name: expect failure
+        if: steps.build.outcome == 'success'
+        run: exit 1
